/**
 * VocabMaster - 词库数据
 * 六大级别核心词汇
 */
const WORD_BANK = {
  cet4: [
    {w:"abandon",p:"/əˈbændən/",pos:"v.",m:"放弃；遗弃",e:"He decided to abandon his plan."},
    {w:"ability",p:"/əˈbɪlɪti/",pos:"n.",m:"能力；才能",e:"She has the ability to learn quickly."},
    {w:"absence",p:"/ˈæbsəns/",pos:"n.",m:"缺席；不在场",e:"His absence was noticed by everyone."},
    {w:"absolute",p:"/ˈæbsəluːt/",pos:"adj.",m:"绝对的；完全的",e:"I have absolute confidence in you."},
    {w:"absorb",p:"/əbˈzɔːrb/",pos:"v.",m:"吸收；全神贯注",e:"Plants absorb carbon dioxide."},
    {w:"abstract",p:"/ˈæbstrækt/",pos:"adj.",m:"抽象的；深奥的",e:"Mathematics can be quite abstract."},
    {w:"abundant",p:"/əˈbʌndənt/",pos:"adj.",m:"丰富的；充裕的",e:"The region has abundant natural resources."},
    {w:"academic",p:"/ˌækəˈdemɪk/",pos:"adj.",m:"学术的；理论的",e:"His academic performance improved greatly."},
    {w:"accelerate",p:"/əkˈseləreɪt/",pos:"v.",m:"加速；促进",e:"The car accelerated rapidly."},
    {w:"access",p:"/ˈækses/",pos:"n.",m:"入口；访问权限",e:"We need access to reliable information."},
    {w:"accomplish",p:"/əˈkɒmplɪʃ/",pos:"v.",m:"完成；实现",e:"She accomplished all her goals."},
    {w:"accurate",p:"/ˈækjərɪt/",pos:"adj.",m:"准确的；精确的",e:"The report must be accurate."},
    {w:"achieve",p:"/əˈtʃiːv/",pos:"v.",m:"实现；达到",e:"Work hard to achieve your dreams."},
    {w:"acquire",p:"/əˈkwaɪər/",pos:"v.",m:"获得；取得",e:"He acquired a valuable new skill."},
    {w:"adapt",p:"/əˈdæpt/",pos:"v.",m:"适应；改编",e:"We must adapt to change quickly."},
    {w:"adequate",p:"/ˈædɪkwɪt/",pos:"adj.",m:"足够的；适当的",e:"The food supply is barely adequate."},
    {w:"adjust",p:"/əˈdʒʌst/",pos:"v.",m:"调整；适应",e:"Please adjust your attitude accordingly."},
    {w:"advance",p:"/ədˈvɑːns/",pos:"v.",m:"前进；进步",e:"Technology advances at a rapid pace."},
    {w:"affair",p:"/əˈfeər/",pos:"n.",m:"事务；事件",e:"This is a private family affair."},
    {w:"affect",p:"/əˈfekt/",pos:"v.",m:"影响；感动",e:"Weather affects our daily mood."},
    {w:"afford",p:"/əˈfɔːrd/",pos:"v.",m:"负担得起；给予",e:"I can't afford a new laptop."},
    {w:"aggressive",p:"/əˈɡresɪv/",pos:"adj.",m:"侵略性的；好斗的",e:"He has an aggressive personality."},
    {w:"ambition",p:"/æmˈbɪʃən/",pos:"n.",m:"野心；抱负",e:"Her ambition is to become a pilot."},
    {w:"analyze",p:"/ˈænəlaɪz/",pos:"v.",m:"分析；解析",e:"We need to analyze the data carefully."},
    {w:"announce",p:"/əˈnaʊns/",pos:"v.",m:"宣布；宣告",e:"They announced the results publicly."},
    {w:"anxiety",p:"/æŋˈzaɪɪti/",pos:"n.",m:"焦虑；担心",e:"Exam anxiety is very common."},
    {w:"apparent",p:"/əˈpærənt/",pos:"adj.",m:"明显的；表面上的",e:"The answer seems apparent."},
    {w:"application",p:"/ˌæplɪˈkeɪʃən/",pos:"n.",m:"申请；应用",e:"Submit your application online."},
    {w:"appropriate",p:"/əˈprəʊpriɪt/",pos:"adj.",m:"适当的；合适的",e:"Choose appropriate clothing for the interview."},
    {w:"approve",p:"/əˈpruːv/",pos:"v.",m:"批准；赞成",e:"The board approved the new plan."},
    {w:"approximately",p:"/əˈprɒksɪmɪtli/",pos:"adv.",m:"大约；近似地",e:"It takes approximately one hour."},
    {w:"arise",p:"/əˈraɪz/",pos:"v.",m:"出现；产生",e:"Problems can arise unexpectedly."},
    {w:"aspect",p:"/ˈæspekt/",pos:"n.",m:"方面；外观",e:"Consider every aspect carefully."},
    {w:"assess",p:"/əˈses/",pos:"v.",m:"评估；评定",e:"Teachers assess student progress regularly."},
    {w:"assign",p:"/əˈsaɪn/",pos:"v.",m:"分配；指派",e:"The teacher assigned extra homework."},
    {w:"assist",p:"/əˈsɪst/",pos:"v.",m:"协助；帮助",e:"I can assist you with that task."},
    {w:"assume",p:"/əˈsjuːm/",pos:"v.",m:"假设；承担",e:"Don't assume you know everything."},
    {w:"atmosphere",p:"/ˈætməsfɪər/",pos:"n.",m:"大气；气氛",e:"The atmosphere was very tense."},
    {w:"attach",p:"/əˈtætʃ/",pos:"v.",m:"附上；连接",e:"Please attach your resume to the email."},
    {w:"attitude",p:"/ˈætɪtjuːd/",pos:"n.",m:"态度；姿态",e:"A positive attitude helps you succeed."},
    {w:"authority",p:"/ɔːˈθɒrɪti/",pos:"n.",m:"权威；当局",e:"Respect the authority of the rules."},
    {w:"available",p:"/əˈveɪləbl/",pos:"adj.",m:"可用的；有空的",e:"Is the room available tonight?"},
    {w:"average",p:"/ˈævərɪdʒ/",pos:"adj.",m:"平均的；普通的",e:"The average score was 80 points."},
    {w:"avoid",p:"/əˈvɔɪd/",pos:"v.",m:"避免；回避",e:"Avoid making careless mistakes."},
    {w:"aware",p:"/əˈweər/",pos:"adj.",m:"意识到的；知道的",e:"Be aware of the potential risks."},
    {w:"balance",p:"/ˈbæləns/",pos:"n.",m:"平衡；结余",e:"Maintain a healthy work-life balance."},
    {w:"barrier",p:"/ˈbæriər/",pos:"n.",m:"障碍；屏障",e:"Language can be a significant barrier."},
    {w:"basis",p:"/ˈbeɪsɪs/",pos:"n.",m:"基础；根据",e:"On the basis of strong evidence."},
    {w:"benefit",p:"/ˈbenɪfɪt/",pos:"n.",m:"好处；利益",e:"Regular exercise benefits your health."},
    {w:"bias",p:"/ˈbaɪəs/",pos:"n.",m:"偏见；偏差",e:"Try your best to avoid bias."},
    {w:"brief",p:"/briːf/",pos:"adj.",m:"简短的；短暂的",e:"Give a brief introduction first."},
    {w:"capable",p:"/ˈkeɪpəbl/",pos:"adj.",m:"有能力的；能干的",e:"She is capable of great achievements."},
    {w:"capacity",p:"/kəˈpæsɪti/",pos:"n.",m:"能力；容量",e:"The hall has a capacity of 500."},
    {w:"capture",p:"/ˈkæptʃər/",pos:"v.",m:"捕获；捕捉",e:"The photo captures the moment perfectly."},
    {w:"challenge",p:"/ˈtʃælɪndʒ/",pos:"n.",m:"挑战；质疑",e:"Face every challenge with courage."},
    {w:"circumstance",p:"/ˈsɜːrkəmstæns/",pos:"n.",m:"情况；环境",e:"Under these difficult circumstances."},
    {w:"claim",p:"/kleɪm/",pos:"v.",m:"声称；主张",e:"He claims to be completely innocent."},
    {w:"collaborate",p:"/kəˈlæbəreɪt/",pos:"v.",m:"合作；协作",e:"We should collaborate more often."},
    {w:"commitment",p:"/kəˈmɪtmənt/",pos:"n.",m:"承诺；投入",e:"Show commitment to your studies."},
    {w:"complex",p:"/ˈkɒmpleks/",pos:"adj.",m:"复杂的；综合的",e:"This is a very complex problem."},
    {w:"concept",p:"/ˈkɒnsept/",pos:"n.",m:"概念；观念",e:"Understand the basic concepts first."},
    {w:"concern",p:"/kənˈsɜːrn/",pos:"n.",m:"关心；担忧",e:"This issue concerns everyone here."},
    {w:"conduct",p:"/ˈkɒndʌkt/",pos:"v.",m:"行为；进行",e:"Conduct a scientific experiment."},
    {w:"conflict",p:"/ˈkɒnflɪkt/",pos:"n.",m:"冲突；矛盾",e:"Resolve the conflict peacefully."},
    {w:"consequence",p:"/ˈkɒnsɪkwɪns/",pos:"n.",m:"后果；结果",e:"Consider the long-term consequences."},
    {w:"considerable",p:"/kənˈsɪdərəbl/",pos:"adj.",m:"相当大的；重要的",e:"A considerable amount of work remains."},
    {w:"consistent",p:"/kənˈsɪstənt/",pos:"adj.",m:"一致的；坚持不懈的",e:"Be consistent in your daily efforts."},
    {w:"contribute",p:"/kənˈtrɪbjuːt/",pos:"v.",m:"贡献；捐助",e:"Everyone should contribute to the team."},
    {w:"controversial",p:"/ˌkɒntrəˈvɜːʃl/",pos:"adj.",m:"有争议的",e:"A highly controversial decision."},
    {w:"convince",p:"/kənˈvɪns/",pos:"v.",m:"说服；使确信",e:"I convinced him to change his mind."},
    {w:"cooperate",p:"/kəʊˈɒpəreɪt/",pos:"v.",m:"合作；配合",e:"We need to cooperate effectively."},
    {w:"crucial",p:"/ˈkruːʃl/",pos:"adj.",m:"至关重要的；关键的",e:"This is a crucial turning point."},
    {w:"cultivate",p:"/ˈkʌltɪveɪt/",pos:"v.",m:"培养；耕作",e:"Cultivate good study habits early."},
    {w:"decline",p:"/dɪˈklaɪn/",pos:"v.",m:"下降；衰退",e:"Sales declined significantly last month."},
    {w:"define",p:"/dɪˈfaɪn/",pos:"v.",m:"定义；界定",e:"Define your goals clearly and precisely."},
    {w:"demonstrate",p:"/ˈdemənstreɪt/",pos:"v.",m:"证明；演示",e:"Demonstrate how the device works."},
    {w:"depend",p:"/dɪˈpend/",pos:"v.",m:"依靠；取决于",e:"Success depends on consistent effort."},
    {w:"determine",p:"/dɪˈtɜːrmɪn/",pos:"v.",m:"决定；确定",e:"Determine the root cause first."},
    {w:"develop",p:"/dɪˈveləp/",pos:"v.",m:"发展；开发",e:"Develop new technologies continuously."},
    {w:"devote",p:"/dɪˈvəʊt/",pos:"v.",m:"献身；专心",e:"Devote yourself to lifelong learning."},
    {w:"dignity",p:"/ˈdɪɡnɪti/",pos:"n.",m:"尊严；高贵",e:"Always maintain your personal dignity."},
    {w:"distribute",p:"/dɪˈstrɪbjuːt/",pos:"v.",m:"分发；分配",e:"Distribute the materials evenly."},
    {w:"diverse",p:"/daɪˈvɜːrs/",pos:"adj.",m:"多样的；不同的",e:"A diverse team is much stronger."},
    {w:"dominant",p:"/ˈdɒmɪnənt/",pos:"adj.",m:"占主导地位的",e:"English is the dominant language worldwide."},
    {w:"elaborate",p:"/ɪˈlæbərɪt/",pos:"v.",m:"详细说明；精心制作",e:"Please elaborate on your idea."},
    {w:"emerge",p:"/ɪˈmɜːrdʒ/",pos:"v.",m:"出现；浮现",e:"A new solution will emerge."},
    {w:"emphasis",p:"/ˈemfəsɪs/",pos:"n.",m:"强调；重点",e:"Put emphasis on quality over speed."},
    {w:"ensure",p:"/ɪnˈʃʊər/",pos:"v.",m:"确保；保证",e:"Ensure your personal safety first."},
    {w:"establish",p:"/ɪˈstæblɪʃ/",pos:"v.",m:"建立；确立",e:"Establish clear and fair rules."},
    {w:"evaluate",p:"/ɪˈvæljueɪt/",pos:"v.",m:"评估；评价",e:"Evaluate the results very carefully."},
    {w:"evident",p:"/ˈevɪdənt/",pos:"adj.",m:"明显的；明白的",e:"It is evident that he was lying."},
    {w:"evolve",p:"/ɪˈvɒlv/",pos:"v.",m:"进化；发展",e:"Language evolves over many centuries."},
    {w:"exclude",p:"/ɪkˈskluːd/",pos:"v.",m:"排除；排斥",e:"Don't exclude anyone from the group."},
    {w:"expand",p:"/ɪkˈspænd/",pos:"v.",m:"扩大；扩展",e:"Expand your vocabulary every day."},
    {w:"explore",p:"/ɪkˈsplɔːr/",pos:"v.",m:"探索；探究",e:"Explore every new possibility carefully."},
    {w:"expose",p:"/ɪkˈspəʊz/",pos:"v.",m:"暴露；使接触",e:"Expose children to different cultures."},
    {w:"extensive",p:"/ɪkˈstensɪv/",pos:"adj.",m:"广泛的；大量的",e:"Extensive research is definitely needed."},
    {w:"factor",p:"/ˈfæktər/",pos:"n.",m:"因素；要素",e:"Many factors affect the final outcome."},
    {w:"familiar",p:"/fəˈmɪliər/",pos:"adj.",m:"熟悉的；常见的",e:"Are you familiar with this topic?"},
    {w:"flexible",p:"/ˈfleksɪbl/",pos:"adj.",m:"灵活的；柔韧的",e:"Stay flexible and open to change."},
    {w:"focus",p:"/ˈfəʊkəs/",pos:"v.",m:"集中；关注",e:"Focus on what truly matters most."},
    {w:"fundamental",p:"/ˌfʌndəˈmentl/",pos:"adj.",m:"基本的；根本的",e:"This is a fundamental human right."},
    {w:"generate",p:"/ˈdʒenəreɪt/",pos:"v.",m:"产生；生成",e:"Generate creative ideas every day."},
    {w:"global",p:"/ˈɡləʊbl/",pos:"adj.",m:"全球的；全世界的",e:"Global warming is a serious problem."},
  ],
  cet6: [
    {w:"abolish",p:"/əˈbɒlɪʃ/",pos:"v.",m:"废除；废止",e:"They voted to abolish the outdated law."},
    {w:"abstain",p:"/əbˈsteɪn/",pos:"v.",m:"放弃；节制",e:"He abstained from voting on the issue."},
    {w:"accommodate",p:"/əˈkɒmədeɪt/",pos:"v.",m:"容纳；适应",e:"Can you accommodate my special request?"},
    {w:"accumulate",p:"/əˈkjuːmjuleɪt/",pos:"v.",m:"积累；积聚",e:"Accumulate knowledge and experience daily."},
    {w:"adhere",p:"/ədˈhɪər/",pos:"v.",m:"坚持；粘附",e:"Adhere to the safety rules strictly."},
    {w:"advocate",p:"/ˈædvəkeɪt/",pos:"v.",m:"倡导；辩护",e:"Advocate for equal education rights."},
    {w:"aesthetic",p:"/iːsˈθetɪk/",pos:"adj.",m:"审美的；美学的",e:"She has great aesthetic sensibility."},
    {w:"aggravate",p:"/ˈæɡrəveɪt/",pos:"v.",m:"加重；激怒",e:"Don't aggravate the difficult situation."},
    {w:"alienate",p:"/ˈeɪliəneɪt/",pos:"v.",m:"疏远；让渡",e:"His behavior alienated all his friends."},
    {w:"alleviate",p:"/əˈliːvieɪt/",pos:"v.",m:"减轻；缓解",e:"Alleviate poverty through better education."},
    {w:"allocate",p:"/ˈæləkeɪt/",pos:"v.",m:"分配；拨出",e:"Allocate resources as wisely as possible."},
    {w:"alternative",p:"/ɔːlˈtɜːrnətɪv/",pos:"n.",m:"替代方案；选择",e:"We need an alternative solution now."},
    {w:"ambiguous",p:"/æmˈbɪɡjuəs/",pos:"adj.",m:"模棱两可的；歧义的",e:"His statement was quite ambiguous."},
    {w:"analogy",p:"/əˈnælədʒi/",pos:"n.",m:"类比；相似之处",e:"Draw an analogy between these two cases."},
    {w:"anticipate",p:"/ænˈtɪsɪpeɪt/",pos:"v.",m:"预料；期待",e:"Anticipate future challenges and prepare."},
    {w:"arbitrary",p:"/ˈɑːrbɪtreri/",pos:"adj.",m:"任意的；武断的",e:"Avoid making arbitrary decisions."},
    {w:"articulate",p:"/ɑːrˈtɪkjuleɪt/",pos:"adj.",m:"表达清晰的",e:"She is very articulate and persuasive."},
    {w:"authentic",p:"/ɔːˈθentɪk/",pos:"adj.",m:"真实的；可信的",e:"This is an authentic historical document."},
    {w:"autonomy",p:"/ɔːˈtɒnəmi/",pos:"n.",m:"自治；自主权",e:"Respect individual autonomy and freedom."},
    {w:"benevolent",p:"/bɪˈnevələnt/",pos:"adj.",m:"仁慈的；善意的",e:"A benevolent leader earns respect."},
    {w:"brevity",p:"/ˈbrevɪti/",pos:"n.",m:"简洁；短暂",e:"Brevity is indeed the soul of wit."},
    {w:"coherent",p:"/kəʊˈhɪərənt/",pos:"adj.",m:"连贯的；一致的",e:"Present a coherent and logical argument."},
    {w:"compassion",p:"/kəmˈpæʃən/",pos:"n.",m:"同情；怜悯",e:"Show compassion and kindness to others."},
    {w:"compensate",p:"/ˈkɒmpenseɪt/",pos:"v.",m:"补偿；弥补",e:"Compensate for the financial loss."},
    {w:"competent",p:"/ˈkɒmpɪtənt/",pos:"adj.",m:"有能力的；足够的",e:"She is a highly competent manager."},
    {w:"comprehensive",p:"/ˌkɒmprɪˈhensɪv/",pos:"adj.",m:"全面的；综合的",e:"A comprehensive and detailed plan."},
    {w:"compulsory",p:"/kəmˈpʌlsəri/",pos:"adj.",m:"强制性的；必须的",e:"Compulsory education is very important."},
    {w:"concede",p:"/kənˈsiːd/",pos:"v.",m:"承认；让步",e:"He finally conceded the argument."},
    {w:"conceive",p:"/kənˈsiːv/",pos:"v.",m:"构想；设计",e:"Conceive a bold and innovative idea."},
    {w:"condense",p:"/kənˈdens/",pos:"v.",m:"压缩；凝结",e:"Condense the report to two pages."},
    {w:"conform",p:"/kənˈfɔːrm/",pos:"v.",m:"遵守；符合",e:"Conform to the established social norms."},
    {w:"confront",p:"/kənˈfrʌnt/",pos:"v.",m:"面对；对抗",e:"Confront your deepest fears directly."},
    {w:"contemplate",p:"/ˈkɒntəmpleɪt/",pos:"v.",m:"沉思；考虑",e:"Contemplate all the possible consequences."},
    {w:"contradict",p:"/ˌkɒntrəˈdɪkt/",pos:"v.",m:"反驳；矛盾",e:"Don't contradict yourself in the argument."},
    {w:"conventional",p:"/kənˈvenʃənl/",pos:"adj.",m:"传统的；习惯的",e:"A conventional and cautious approach."},
    {w:"corruption",p:"/kəˈrʌpʃən/",pos:"n.",m:"腐败；堕落",e:"Fight against corruption at every level."},
    {w:"criterion",p:"/kraɪˈtɪəriən/",pos:"n.",m:"标准；准则",e:"Set clear criteria for evaluation."},
    {w:"cynical",p:"/ˈsɪnɪkl/",pos:"adj.",m:"愤世嫉俗的",e:"Don't be cynical about life's possibilities."},
    {w:"deduce",p:"/dɪˈdjuːs/",pos:"v.",m:"推断；演绎",e:"Deduce the answer through logical reasoning."},
    {w:"deficiency",p:"/dɪˈfɪʃənsi/",pos:"n.",m:"缺乏；不足",e:"Vitamin D deficiency is very common."},
    {w:"deliberate",p:"/dɪˈlɪbərɪt/",pos:"adj.",m:"故意的；深思熟虑的",e:"It was a very deliberate choice."},
    {w:"deprive",p:"/dɪˈpraɪv/",pos:"v.",m:"剥夺；使丧失",e:"Don't deprive others of their rights."},
    {w:"deteriorate",p:"/dɪˈtɪəriəreɪt/",pos:"v.",m:"恶化；退化",e:"His health is rapidly deteriorating."},
    {w:"dilemma",p:"/dɪˈlemə/",pos:"n.",m:"困境；进退两难",e:"Face a difficult moral dilemma."},
    {w:"diplomatic",p:"/ˌdɪpləˈmætɪk/",pos:"adj.",m:"外交的；老练的",e:"Give a diplomatic and tactful response."},
    {w:"discriminate",p:"/dɪˈskrɪmɪneɪt/",pos:"v.",m:"歧视；区分",e:"Never discriminate against others."},
    {w:"disrupt",p:"/dɪsˈrʌpt/",pos:"v.",m:"破坏；扰乱",e:"New technology disrupts traditional industries."},
    {w:"diverge",p:"/daɪˈvɜːrdʒ/",pos:"v.",m:"分叉；偏离",e:"Their opinions diverge on this matter."},
    {w:"dominant",p:"/ˈdɒmɪnənt/",pos:"adj.",m:"主导的；占优势的",e:"The dominant culture shapes society."},
    {w:"dubious",p:"/ˈdjuːbiəs/",pos:"adj.",m:"可疑的；半信半疑的",e:"His claim is quite dubious."},
    {w:"elaborate",p:"/ɪˈlæbərɪt/",pos:"v.",m:"详细说明；精心制作",e:"Please elaborate further on your plan."},
    {w:"eloquent",p:"/ˈeləkwənt/",pos:"adj.",m:"雄辩的；有说服力的",e:"An eloquent and inspiring speaker."},
    {w:"enforce",p:"/ɪnˈfɔːrs/",pos:"v.",m:"执行；强制",e:"Enforce the rules fairly and consistently."},
    {w:"enhance",p:"/ɪnˈhɑːns/",pos:"v.",m:"提高；增强",e:"Enhance your professional skills."},
    {w:"entail",p:"/ɪnˈteɪl/",pos:"v.",m:"必然包含；需要",e:"The project entails significant risks."},
    {w:"erode",p:"/ɪˈrəʊd/",pos:"v.",m:"侵蚀；腐蚀",e:"Waves erode the coastal cliffs."},
    {w:"exaggerate",p:"/ɪɡˈzædʒəreɪt/",pos:"v.",m:"夸大；夸张",e:"Don't exaggerate the actual situation."},
    {w:"exceed",p:"/ɪkˈsiːd/",pos:"v.",m:"超过；超越",e:"The cost should not exceed the budget."},
    {w:"exert",p:"/ɪɡˈzɜːrt/",pos:"v.",m:"施加；发挥",e:"Exert great influence on society."},
    {w:"explicit",p:"/ɪkˈsplɪsɪt/",pos:"adj.",m:"明确的；清楚的",e:"Provide explicit instructions always."},
    {w:"exploit",p:"/ɪkˈsplɔɪt/",pos:"v.",m:"利用；开发",e:"Exploit every available opportunity."},
    {w:"facilitate",p:"/fəˈsɪlɪteɪt/",pos:"v.",m:"促进；使容易",e:"Facilitate better communication."},
    {w:"fluctuate",p:"/ˈflʌktʃueɪt/",pos:"v.",m:"波动；起伏",e:"Prices fluctuate with the market."},
    {w:"formulate",p:"/ˈfɔːrmjuleɪt/",pos:"v.",m:"制定；阐明",e:"Formulate a clear and effective strategy."},
    {w:"fragile",p:"/ˈfrædʒaɪl/",pos:"adj.",m:"脆弱的；易碎的",e:"Handle fragile items with great care."},
    {w:"generate",p:"/ˈdʒenəreɪt/",pos:"v.",m:"产生；生成",e:"Generate innovative and creative ideas."},
    {w:"genuine",p:"/ˈdʒenjuɪn/",pos:"adj.",m:"真实的；真诚的",e:"Show genuine interest and concern."},
    {w:"hierarchy",p:"/ˈhaɪərɑːrki/",pos:"n.",m:"等级制度；层次",e:"A strict organizational hierarchy."},
    {w:"hypothesis",p:"/haɪˈpɒθɪsɪs/",pos:"n.",m:"假说；假设",e:"Test your hypothesis with experiments."},
    {w:"illuminate",p:"/ɪˈluːmɪneɪt/",pos:"v.",m:"照亮；阐明",e:"Illuminate the key points clearly."},
    {w:"implication",p:"/ˌɪmplɪˈkeɪʃən/",pos:"n.",m:"含义；暗示",e:"Consider all the broader implications."},
    {w:"incentive",p:"/ɪnˈsentɪv/",pos:"n.",m:"激励；奖励",e:"Provide strong incentives for performance."},
    {w:"indispensable",p:"/ˌɪndɪˈspensəbl/",pos:"adj.",m:"不可或缺的",e:"Water is absolutely indispensable for life."},
    {w:"inevitable",p:"/ɪnˈevɪtəbl/",pos:"adj.",m:"不可避免的",e:"Change is ultimately inevitable."},
    {w:"innovation",p:"/ˌɪnəˈveɪʃən/",pos:"n.",m:"创新；革新",e:"Encourage innovation in every team."},
    {w:"integrity",p:"/ɪnˈteɡrɪti/",pos:"n.",m:"诚信；完整性",e:"Integrity is the foundation of trust."},
    {w:"interpret",p:"/ɪnˈtɜːrprɪt/",pos:"v.",m:"解释；翻译",e:"Interpret the data objectively."},
    {w:"intervene",p:"/ˌɪntərˈviːn/",pos:"v.",m:"干预；介入",e:"The government decided to intervene."},
    {w:"intuition",p:"/ˌɪntjuˈɪʃən/",pos:"n.",m:"直觉；直觉力",e:"Trust your intuition sometimes."},
    {w:"justify",p:"/ˈdʒʌstɪfaɪ/",pos:"v.",m:"证明…正当；辩护",e:"Justify every major decision carefully."},
    {w:"legitimate",p:"/lɪˈdʒɪtɪmɪt/",pos:"adj.",m:"合法的；正当的",e:"A legitimate and legal business."},
    {w:"manipulate",p:"/məˈnɪpjuleɪt/",pos:"v.",m:"操控；操纵",e:"Don't manipulate others unfairly."},
    {w:"mechanism",p:"/ˈmekənɪzəm/",pos:"n.",m:"机制；机械装置",e:"Understand the underlying mechanism."},
    {w:"mediate",p:"/ˈmiːdieɪt/",pos:"v.",m:"调解；斡旋",e:"Mediate between the two parties."},
    {w:"meticulous",p:"/məˈtɪkjələs/",pos:"adj.",m:"一丝不苟的；细致的",e:"Meticulous attention to every detail."},
    {w:"migration",p:"/maɪˈɡreɪʃən/",pos:"n.",m:"迁徙；移民",e:"Study bird migration patterns."},
    {w:"minimize",p:"/ˈmɪnɪmaɪz/",pos:"v.",m:"最小化；减少",e:"Minimize the risk of failure."},
    {w:"misconception",p:"/ˌmɪskənˈsepʃən/",pos:"n.",m:"误解；错误观念",e:"Correct common misconceptions."},
    {w:"moderate",p:"/ˈmɒdərɪt/",pos:"adj.",m:"适度的；温和的",e:"Take a moderate and balanced approach."},
    {w:"momentum",p:"/məˈmentəm/",pos:"n.",m:"动力；势头",e:"Build momentum through early wins."},
    {w:"naive",p:"/naɪˈiːv/",pos:"adj.",m:"天真的；幼稚的",e:"Don't be naive about the dangers."},
    {w:"negligible",p:"/ˈneɡlɪdʒɪbl/",pos:"adj.",m:"微不足道的",e:"The difference is negligible."},
  ],
  postgrad: [
    {w:"abdicate",p:"/ˈæbdɪkeɪt/",pos:"v.",m:"放弃（权力）；退位",e:"He abdicated all his responsibility."},
    {w:"aberrant",p:"/æˈberənt/",pos:"adj.",m:"异常的；越轨的",e:"Aberrant behavior needs immediate attention."},
    {w:"abject",p:"/ˈæbdʒekt/",pos:"adj.",m:"极悲惨的；卑鄙的",e:"Living in abject poverty is unacceptable."},
    {w:"abrogate",p:"/ˈæbrəɡeɪt/",pos:"v.",m:"废除；取消（法令）",e:"Abrogate the outdated treaty."},
    {w:"abstemious",p:"/æbˈstiːmiəs/",pos:"adj.",m:"有节制的；节食的",e:"Lead an abstemious lifestyle."},
    {w:"acrimonious",p:"/ˌækrɪˈməʊniəs/",pos:"adj.",m:"尖刻的；充满敌意的",e:"An acrimonious and heated debate."},
    {w:"admonish",p:"/ədˈmɒnɪʃ/",pos:"v.",m:"劝告；告诫",e:"He admonished the careless students."},
    {w:"affable",p:"/ˈæfəbl/",pos:"adj.",m:"和蔼可亲的；友善的",e:"An affable and approachable professor."},
    {w:"affluent",p:"/ˈæfluənt/",pos:"adj.",m:"富裕的；丰富的",e:"An affluent and prosperous neighborhood."},
    {w:"allegory",p:"/ˈæləɡɔːri/",pos:"n.",m:"寓言；讽喻",e:"The novel is an allegory about power."},
    {w:"aloof",p:"/əˈluːf/",pos:"adj.",m:"冷漠的；疏远的",e:"She remained aloof from the drama."},
    {w:"altruism",p:"/ˈæltruɪzəm/",pos:"n.",m:"利他主义；无私奉献",e:"True altruism benefits all of society."},
    {w:"ambivalent",p:"/æmˈbɪvələnt/",pos:"adj.",m:"矛盾的；摇摆不定的",e:"I feel deeply ambivalent about this."},
    {w:"ameliorate",p:"/əˈmiːliəreɪt/",pos:"v.",m:"改善；改良",e:"Ameliorate the poor living conditions."},
    {w:"anachronism",p:"/əˈnækrənɪzəm/",pos:"n.",m:"时代错误；过时的事物",e:"This policy is a clear anachronism."},
    {w:"anecdote",p:"/ˈænɪkdəʊt/",pos:"n.",m:"轶事；奇闻趣事",e:"He told an amusing personal anecdote."},
    {w:"antagonize",p:"/ænˈtæɡənaɪz/",pos:"v.",m:"激怒；使对立",e:"Don't antagonize your close colleagues."},
    {w:"apathy",p:"/ˈæpəθi/",pos:"n.",m:"冷漠；无兴趣",e:"Voter apathy is a serious problem."},
    {w:"appease",p:"/əˈpiːz/",pos:"v.",m:"安抚；平息",e:"Appease their anger through negotiation."},
    {w:"archaic",p:"/ɑːrˈkeɪɪk/",pos:"adj.",m:"古老的；已不通用的",e:"Archaic language is difficult to understand."},
    {w:"arduous",p:"/ˈɑːrdʒuəs/",pos:"adj.",m:"艰难的；费力的",e:"An arduous and challenging journey."},
    {w:"ascertain",p:"/ˌæsərˈteɪn/",pos:"v.",m:"确定；查明",e:"Ascertain all the relevant facts first."},
    {w:"astute",p:"/əˈstjuːt/",pos:"adj.",m:"精明的；机敏的",e:"An astute and savvy businessperson."},
    {w:"atrophy",p:"/ˈætrəfi/",pos:"v.",m:"萎缩；衰退",e:"Muscles atrophy without regular exercise."},
    {w:"audacious",p:"/ɔːˈdeɪʃəs/",pos:"adj.",m:"大胆的；鲁莽的",e:"An audacious and daring plan."},
    {w:"austere",p:"/ɒˈstɪər/",pos:"adj.",m:"简朴的；严峻的",e:"An austere and frugal lifestyle."},
    {w:"axiom",p:"/ˈæksiəm/",pos:"n.",m:"公理；不证自明的道理",e:"A fundamental mathematical axiom."},
    {w:"belittle",p:"/bɪˈlɪtl/",pos:"v.",m:"贬低；轻视",e:"Don't belittle others' sincere efforts."},
    {w:"benign",p:"/bɪˈnaɪn/",pos:"adj.",m:"良性的；和善的",e:"A benign tumor is not dangerous."},
    {w:"berate",p:"/bɪˈreɪt/",pos:"v.",m:"严厉责骂；训斥",e:"The boss berated the entire team."},
    {w:"clandestine",p:"/klænˈdestɪn/",pos:"adj.",m:"秘密的；隐蔽的",e:"A clandestine and covert operation."},
    {w:"coerce",p:"/kəʊˈɜːrs/",pos:"v.",m:"强迫；胁迫",e:"You cannot coerce people to agree."},
    {w:"cogent",p:"/ˈkəʊdʒənt/",pos:"adj.",m:"有说服力的；令人信服的",e:"A cogent and well-reasoned argument."},
    {w:"convoluted",p:"/ˈkɒnvəluːtɪd/",pos:"adj.",m:"错综复杂的；费解的",e:"A convoluted and confusing plot."},
    {w:"corroborate",p:"/kəˈrɒbəreɪt/",pos:"v.",m:"证实；支持",e:"Corroborate the claims with evidence."},
    {w:"credulous",p:"/ˈkredjələs/",pos:"adj.",m:"轻信的；易受骗的",e:"Don't be too credulous of strangers."},
    {w:"cryptic",p:"/ˈkrɪptɪk/",pos:"adj.",m:"神秘的；含义模糊的",e:"A cryptic and puzzling message."},
    {w:"dearth",p:"/dɜːrθ/",pos:"n.",m:"缺乏；稀少",e:"A dearth of qualified candidates."},
    {w:"deference",p:"/ˈdefərəns/",pos:"n.",m:"尊重；顺从",e:"Show proper deference to elders."},
    {w:"delineate",p:"/dɪˈlɪnieɪt/",pos:"v.",m:"描述；勾勒出",e:"Delineate the boundaries clearly."},
    {w:"denounce",p:"/dɪˈnaʊns/",pos:"v.",m:"谴责；告发",e:"Denounce corruption publicly."},
    {w:"deride",p:"/dɪˈraɪd/",pos:"v.",m:"嘲笑；嘲弄",e:"Don't deride others' sincere efforts."},
    {w:"desolate",p:"/ˈdesələt/",pos:"adj.",m:"荒凉的；孤寂的",e:"A desolate and barren landscape."},
    {w:"dichotomy",p:"/daɪˈkɒtəmi/",pos:"n.",m:"二分法；对立",e:"The dichotomy between theory and practice."},
    {w:"diffident",p:"/ˈdɪfɪdənt/",pos:"adj.",m:"缺乏自信的；羞怯的",e:"A diffident but talented student."},
    {w:"dilettante",p:"/ˌdɪlɪˈtænti/",pos:"n.",m:"业余爱好者；浅尝者",e:"A dilettante in many fields."},
    {w:"discern",p:"/dɪˈsɜːrn/",pos:"v.",m:"辨别；识别",e:"Discern the true from the false."},
    {w:"disparate",p:"/ˈdɪspərɪt/",pos:"adj.",m:"完全不同的；不相关的",e:"Disparate and seemingly unrelated ideas."},
    {w:"disseminate",p:"/dɪˈsemɪneɪt/",pos:"v.",m:"传播；散布",e:"Disseminate knowledge widely."},
    {w:"divergent",p:"/daɪˈvɜːrdʒənt/",pos:"adj.",m:"分歧的；相异的",e:"Divergent views on the same issue."},
    {w:"dogmatic",p:"/dɒɡˈmætɪk/",pos:"adj.",m:"教条的；武断的",e:"Avoid being too dogmatic."},
  ],
  toefl: [
    {w:"aberration",p:"/ˌæbəˈreɪʃən/",pos:"n.",m:"偏差；异常现象",e:"This result is a statistical aberration."},
    {w:"abhor",p:"/əbˈhɔːr/",pos:"v.",m:"憎恶；极度讨厌",e:"She abhors all forms of violence."},
    {w:"abyss",p:"/əˈbɪs/",pos:"n.",m:"深渊；无底洞",e:"Staring into the dark abyss."},
    {w:"accrue",p:"/əˈkruː/",pos:"v.",m:"积累；自然增加",e:"Interest accrues slowly over time."},
    {w:"acumen",p:"/ˈækjumɪn/",pos:"n.",m:"敏锐；洞察力",e:"Sharp business acumen is essential."},
    {w:"adamant",p:"/ˈædəmənt/",pos:"adj.",m:"坚定的；固执己见的",e:"She was absolutely adamant in her refusal."},
    {w:"adept",p:"/ˈædept/",pos:"adj.",m:"熟练的；擅长的",e:"She is highly adept at languages."},
    {w:"adroit",p:"/əˈdrɔɪt/",pos:"adj.",m:"灵巧的；机敏的",e:"An adroit and skilled negotiator."},
    {w:"advent",p:"/ˈædvɪnt/",pos:"n.",m:"出现；来临",e:"The advent of the internet changed everything."},
    {w:"adversity",p:"/ədˈvɜːrsɪti/",pos:"n.",m:"逆境；不幸",e:"Rise above every adversity."},
    {w:"affinity",p:"/əˈfɪnɪti/",pos:"n.",m:"亲近；吸引力",e:"She felt a strong affinity with him."},
    {w:"agitate",p:"/ˈædʒɪteɪt/",pos:"v.",m:"使不安；激动",e:"The breaking news agitated everyone."},
    {w:"allude",p:"/əˈluːd/",pos:"v.",m:"暗指；间接提到",e:"He alluded to the underlying problem."},
    {w:"altercation",p:"/ˌɔːltərˈkeɪʃən/",pos:"n.",m:"争吵；口角",e:"A heated verbal altercation ensued."},
    {w:"altruistic",p:"/ˌæltruˈɪstɪk/",pos:"adj.",m:"利他的；无私的",e:"A genuinely altruistic act."},
    {w:"amalgamate",p:"/əˈmælɡəmeɪt/",pos:"v.",m:"合并；混合",e:"The two companies finally amalgamated."},
    {w:"ambivalence",p:"/æmˈbɪvələns/",pos:"n.",m:"矛盾心理；犹豫不决",e:"His deep ambivalence was clearly obvious."},
    {w:"amend",p:"/əˈmend/",pos:"v.",m:"修改；改进",e:"Amend the outdated constitution."},
    {w:"amiable",p:"/ˈeɪmiəbl/",pos:"adj.",m:"和蔼可亲的；友好的",e:"An amiable and pleasant colleague."},
    {w:"amorphous",p:"/əˈmɔːrfəs/",pos:"adj.",m:"无固定形状的；模糊的",e:"An amorphous and ill-defined structure."},
    {w:"anarchy",p:"/ˈænərki/",pos:"n.",m:"无政府状态；混乱",e:"Total anarchy suddenly broke out."},
    {w:"anomaly",p:"/əˈnɒməli/",pos:"n.",m:"异常；反常现象",e:"This is a significant statistical anomaly."},
    {w:"antagonism",p:"/ænˈtæɡənɪzəm/",pos:"n.",m:"对抗；强烈敌意",e:"Deep antagonism exists between them."},
    {w:"antiquated",p:"/ˈæntɪkweɪtɪd/",pos:"adj.",m:"过时的；陈旧的",e:"An antiquated and outdated system."},
    {w:"apprehension",p:"/ˌæprɪˈhenʃən/",pos:"n.",m:"忧虑；理解；逮捕",e:"Feel great apprehension about the future."},
    {w:"apt",p:"/æpt/",pos:"adj.",m:"恰当的；有倾向的",e:"An apt and fitting description."},
    {w:"ardent",p:"/ˈɑːrdənt/",pos:"adj.",m:"热情的；热切的",e:"An ardent and passionate supporter."},
    {w:"articulation",p:"/ɑːrˌtɪkjuˈleɪʃən/",pos:"n.",m:"清楚表达；发音",e:"Clear articulation is very important."},
    {w:"aspire",p:"/əˈspaɪər/",pos:"v.",m:"渴望；有志于",e:"Aspire to achieve great things."},
    {w:"assiduous",p:"/əˈsɪdjuəs/",pos:"adj.",m:"勤勉的；刻苦的",e:"An assiduous and hardworking student."},
    {w:"assuage",p:"/əˈsweɪdʒ/",pos:"v.",m:"缓和；平息",e:"Assuage fears with clear information."},
    {w:"attest",p:"/əˈtest/",pos:"v.",m:"证明；证实",e:"Attest to the authenticity."},
    {w:"austere",p:"/ɒˈstɪər/",pos:"adj.",m:"简朴的；严格的",e:"An austere and disciplined lifestyle."},
    {w:"avarice",p:"/ˈævərɪs/",pos:"n.",m:"贪婪；贪财",e:"Avarice leads to moral corruption."},
    {w:"aversion",p:"/əˈvɜːrʃən/",pos:"n.",m:"厌恶；反感",e:"A strong aversion to dishonesty."},
    {w:"benevolence",p:"/bɪˈnevələns/",pos:"n.",m:"善意；仁慈",e:"Show true benevolence to others."},
    {w:"bewilder",p:"/bɪˈwɪldər/",pos:"v.",m:"使困惑；使迷惑",e:"The complex situation bewildered everyone."},
    {w:"blatant",p:"/ˈbleɪtənt/",pos:"adj.",m:"公然的；明目张胆的",e:"A blatant and obvious lie."},
    {w:"bolster",p:"/ˈbəʊlstər/",pos:"v.",m:"支撑；加强",e:"Bolster your confidence."},
    {w:"burgeon",p:"/ˈbɜːrdʒən/",pos:"v.",m:"迅速发展；萌发",e:"A burgeoning new industry."},
    {w:"capricious",p:"/kəˈprɪʃəs/",pos:"adj.",m:"变化无常的；任性的",e:"Capricious and unpredictable weather."},
    {w:"catalyst",p:"/ˈkætəlɪst/",pos:"n.",m:"催化剂；促进因素",e:"Act as a catalyst for real change."},
    {w:"caustic",p:"/ˈkɔːstɪk/",pos:"adj.",m:"腐蚀性的；尖刻的",e:"A caustic and biting remark."},
    {w:"circumspect",p:"/ˈsɜːrkəmspekt/",pos:"adj.",m:"谨慎的；小心的",e:"Be circumspect in all your actions."},
    {w:"clamor",p:"/ˈklæmər/",pos:"n.",m:"喧嚣；强烈要求",e:"The clamor for change grew louder."},
    {w:"coalesce",p:"/ˌkəʊəˈles/",pos:"v.",m:"合并；联合",e:"The groups coalesced into one movement."},
    {w:"cogitate",p:"/ˈkɒdʒɪteɪt/",pos:"v.",m:"深思；思考",e:"Cogitate carefully on this issue."},
    {w:"commensurate",p:"/kəˈmenʃərɪt/",pos:"adj.",m:"相称的；相当的",e:"Salary commensurate with experience."},
    {w:"compendium",p:"/kəmˈpendiəm/",pos:"n.",m:"纲要；简编",e:"A comprehensive compendium of knowledge."},
    {w:"conciliate",p:"/kənˈsɪlieɪt/",pos:"v.",m:"安抚；调停",e:"Conciliate the opposing parties."},
    {w:"conundrum",p:"/kəˈnʌndrəm/",pos:"n.",m:"难题；谜语",e:"Face a difficult ethical conundrum."},
  ],
  ielts: [
    {w:"abstraction",p:"/æbˈstrækʃən/",pos:"n.",m:"抽象；抽象概念",e:"Think in abstraction and metaphor."},
    {w:"accountability",p:"/əˌkaʊntəˈbɪlɪti/",pos:"n.",m:"责任；问责制",e:"Accountability is absolutely essential."},
    {w:"acrimony",p:"/ˈækrɪməni/",pos:"n.",m:"尖刻；辛辣",e:"The debate was full of acrimony."},
    {w:"affirmative",p:"/əˈfɜːrmətɪv/",pos:"adj.",m:"肯定的；赞成的",e:"Give a clear affirmative answer."},
    {w:"aftermath",p:"/ˈɑːftərmæθ/",pos:"n.",m:"后果；余波",e:"Deal with the aftermath of the war."},
    {w:"aggregate",p:"/ˈæɡrɪɡɪt/",pos:"n.",m:"总计；集合体",e:"In the aggregate they did well."},
    {w:"albeit",p:"/ɔːlˈbiːɪt/",pos:"conj.",m:"尽管；虽然",e:"She succeeded, albeit very slowly."},
    {w:"alienation",p:"/ˌeɪliəˈneɪʃən/",pos:"n.",m:"疏远；异化",e:"A sense of deep alienation."},
    {w:"allegation",p:"/ˌæləˈɡeɪʃən/",pos:"n.",m:"指控；声称",e:"Serious allegations were publicly made."},
    {w:"allusion",p:"/əˈluːʒən/",pos:"n.",m:"暗指；间接提及",e:"Literary allusions in the text."},
    {w:"ambiguity",p:"/ˌæmbɪˈɡjuːɪti/",pos:"n.",m:"歧义；模糊性",e:"Avoid ambiguity in all writing."},
    {w:"amicable",p:"/ˈæmɪkəbl/",pos:"adj.",m:"友好的；和睦的",e:"Reach an amicable settlement."},
    {w:"amplify",p:"/ˈæmplɪfaɪ/",pos:"v.",m:"放大；扩大",e:"Amplify the sound clearly."},
    {w:"analogous",p:"/əˈnæləɡəs/",pos:"adj.",m:"类似的；相似的",e:"Analogous situations require similar solutions."},
    {w:"anecdotal",p:"/ˌænɪkˈdəʊtl/",pos:"adj.",m:"奇闻的；道听途说的",e:"Anecdotal evidence is not reliable."},
    {w:"animosity",p:"/ˌænɪˈmɒsɪti/",pos:"n.",m:"仇恨；强烈敌意",e:"Deep animosity between bitter rivals."},
    {w:"annotate",p:"/ˈænəteɪt/",pos:"v.",m:"注释；注解",e:"Annotate the important document."},
    {w:"anomalous",p:"/əˈnɒmələs/",pos:"adj.",m:"不规则的；异常的",e:"Anomalous and unexpected behavior."},
    {w:"aphorism",p:"/ˈæfərɪzəm/",pos:"n.",m:"格言；警句",e:"A wise and timeless aphorism."},
    {w:"apt",p:"/æpt/",pos:"adj.",m:"恰当的；有倾向的",e:"An apt and accurate description."},
    {w:"articulate",p:"/ɑːrˈtɪkjuleɪt/",pos:"v.",m:"清楚表达；发音清晰",e:"Articulate your ideas more clearly."},
    {w:"assimilation",p:"/əˌsɪmɪˈleɪʃən/",pos:"n.",m:"同化；吸收",e:"Cultural assimilation takes many years."},
    {w:"attrition",p:"/əˈtrɪʃən/",pos:"n.",m:"磨耗；消耗",e:"Win by a war of attrition."},
    {w:"augment",p:"/ɔːɡˈment/",pos:"v.",m:"增加；扩大",e:"Augment your income significantly."},
    {w:"auspicious",p:"/ɔːˈspɪʃəs/",pos:"adj.",m:"吉祥的；吉兆的",e:"An auspicious start to the year."},
    {w:"autonomy",p:"/ɔːˈtɒnəmi/",pos:"n.",m:"自治；自主权",e:"Respect complete individual autonomy."},
    {w:"banal",p:"/bəˈnɑːl/",pos:"adj.",m:"陈腐的；平庸的",e:"Avoid banal and clichéd writing."},
    {w:"benchmark",p:"/ˈbentʃmɑːrk/",pos:"n.",m:"基准；标准",e:"Set a high benchmark for quality."},
    {w:"benign",p:"/bɪˈnaɪn/",pos:"adj.",m:"良性的；和善的",e:"A benign and gentle influence."},
    {w:"bolster",p:"/ˈbəʊlstər/",pos:"v.",m:"支撑；加强",e:"Bolster the economy through investment."},
    {w:"brevity",p:"/ˈbrevɪti/",pos:"n.",m:"简洁；短暂",e:"Aim for clarity and brevity."},
    {w:"bureaucracy",p:"/bjʊˈrɒkrəsi/",pos:"n.",m:"官僚机构；繁文缛节",e:"Reduce excessive bureaucracy."},
    {w:"catalyst",p:"/ˈkætəlɪst/",pos:"n.",m:"催化剂；促进因素",e:"Education acts as a social catalyst."},
    {w:"cogent",p:"/ˈkəʊdʒənt/",pos:"adj.",m:"有说服力的；令人信服的",e:"A cogent and well-structured argument."},
    {w:"cohesion",p:"/kəʊˈhiːʒən/",pos:"n.",m:"凝聚力；结合",e:"Social cohesion is very important."},
    {w:"collateral",p:"/kəˈlætərəl/",pos:"adj.",m:"附带的；抵押品",e:"Collateral damage should be minimized."},
    {w:"commodify",p:"/kəˈmɒdɪfaɪ/",pos:"v.",m:"商品化",e:"Don't commodify every human experience."},
    {w:"complacency",p:"/kəmˈpleɪsənsi/",pos:"n.",m:"自满；自鸣得意",e:"Avoid complacency at all costs."},
    {w:"comply",p:"/kəmˈplaɪ/",pos:"v.",m:"遵从；依从",e:"Comply with all relevant regulations."},
    {w:"conceivable",p:"/kənˈsiːvəbl/",pos:"adj.",m:"可以想象的；可能的",e:"Every conceivable scenario."},
    {w:"conducive",p:"/kənˈdjuːsɪv/",pos:"adj.",m:"有助于；有利于",e:"An environment conducive to learning."},
    {w:"conjecture",p:"/kənˈdʒektʃər/",pos:"n.",m:"猜想；猜测",e:"A mere conjecture without evidence."},
    {w:"consolidate",p:"/kənˈsɒlɪdeɪt/",pos:"v.",m:"巩固；合并",e:"Consolidate your financial position."},
    {w:"contentious",p:"/kənˈtenʃəs/",pos:"adj.",m:"有争议的；好争论的",e:"A highly contentious political issue."},
    {w:"contraband",p:"/ˈkɒntrəbænd/",pos:"n.",m:"走私品；违禁品",e:"Seize all contraband goods."},
    {w:"contrite",p:"/kənˈtraɪt/",pos:"adj.",m:"悔恨的；痛悔的",e:"Feeling contrite about past mistakes."},
    {w:"copious",p:"/ˈkəʊpiəs/",pos:"adj.",m:"大量的；丰富的",e:"Take copious notes during the lecture."},
    {w:"correlate",p:"/ˈkɒrəleɪt/",pos:"v.",m:"关联；相互关系",e:"Correlate the various data sets."},
    {w:"credibility",p:"/ˌkredɪˈbɪlɪti/",pos:"n.",m:"可信度；可靠性",e:"Maintain your professional credibility."},
    {w:"criterion",p:"/kraɪˈtɪəriən/",pos:"n.",m:"标准；评判准则",e:"A clear evaluation criterion."},
    {w:"curb",p:"/kɜːrb/",pos:"v.",m:"控制；抑制",e:"Curb your strong emotions."},
  ],
  gre: [
    {w:"abase",p:"/əˈbeɪs/",pos:"v.",m:"贬低；降低…的地位",e:"He debased himself completely."},
    {w:"abate",p:"/əˈbeɪt/",pos:"v.",m:"减弱；减少",e:"The violent storm finally abated."},
    {w:"abscond",p:"/æbˈskɒnd/",pos:"v.",m:"潜逃；逃跑",e:"Abscond with all the money."},
    {w:"abstruse",p:"/æbˈstruːs/",pos:"adj.",m:"深奥难懂的",e:"An abstruse philosophical text."},
    {w:"accretion",p:"/əˈkriːʃən/",pos:"n.",m:"增长；积聚",e:"Slow accretion of scientific knowledge."},
    {w:"acerbic",p:"/əˈsɜːrbɪk/",pos:"adj.",m:"尖刻的；苦涩的",e:"Acerbic and cutting criticism."},
    {w:"acrimony",p:"/ˈækrɪməni/",pos:"n.",m:"尖刻；辛辣",e:"Deep marital acrimony."},
    {w:"adumbrate",p:"/ˈædʌmbreɪt/",pos:"v.",m:"概述；预示",e:"Adumbrate the overall plan."},
    {w:"aegis",p:"/ˈiːdʒɪs/",pos:"n.",m:"保护；庇护",e:"Under the strong aegis of law."},
    {w:"alacrity",p:"/əˈlækrɪti/",pos:"n.",m:"敏捷；热切",e:"Accept the offer with great alacrity."},
    {w:"allay",p:"/əˈleɪ/",pos:"v.",m:"减轻；缓和",e:"Allay someone's deepest fears."},
    {w:"amalgam",p:"/əˈmælɡəm/",pos:"n.",m:"混合物；汞齐",e:"An amalgam of very different ideas."},
    {w:"amenity",p:"/əˈmenɪti/",pos:"n.",m:"便利设施；宜人",e:"Modern urban amenities."},
    {w:"anachronistic",p:"/əˌnækrəˈnɪstɪk/",pos:"adj.",m:"过时的；时代错误的",e:"An anachronistic worldview."},
    {w:"animus",p:"/ˈænɪməs/",pos:"n.",m:"敌意；强烈反感",e:"Deep animus toward rivals."},
    {w:"anomie",p:"/ˈænəmi/",pos:"n.",m:"社会失范；迷失",e:"Social anomie in modern cities."},
    {w:"antithesis",p:"/ænˈtɪθɪsɪs/",pos:"n.",m:"对立面；对比",e:"The antithesis of good leadership."},
    {w:"apocryphal",p:"/əˈpɒkrɪfəl/",pos:"adj.",m:"来源可疑的；虚假的",e:"An apocryphal historical story."},
    {w:"apostate",p:"/əˈpɒsteɪt/",pos:"n.",m:"变节者；背叛者",e:"Labeled a political apostate."},
    {w:"approbation",p:"/ˌæprəˈbeɪʃən/",pos:"n.",m:"赞许；批准",e:"Seek official approbation."},
    {w:"apt",p:"/æpt/",pos:"adj.",m:"恰当的；敏捷的",e:"A particularly apt metaphor."},
    {w:"arcane",p:"/ɑːrˈkeɪn/",pos:"adj.",m:"神秘的；鲜为人知的",e:"Arcane and esoteric knowledge."},
    {w:"ardor",p:"/ˈɑːrdər/",pos:"n.",m:"热情；热忱",e:"Pursue with youthful ardor."},
    {w:"ascetic",p:"/əˈsetɪk/",pos:"adj.",m:"禁欲的；苦行的",e:"An ascetic and austere lifestyle."},
    {w:"asperity",p:"/æˈsperɪti/",pos:"n.",m:"严酷；刻薄",e:"Respond with great asperity."},
    {w:"assiduous",p:"/əˈsɪdjuəs/",pos:"adj.",m:"勤勉的；孜孜不倦的",e:"An assiduous and devoted student."},
    {w:"assuage",p:"/əˈsweɪdʒ/",pos:"v.",m:"缓和；减轻",e:"Assuage guilt through good deeds."},
    {w:"avarice",p:"/ˈævərɪs/",pos:"n.",m:"贪婪；贪财",e:"Avarice destroys human relationships."},
    {w:"aversion",p:"/əˈvɜːrʃən/",pos:"n.",m:"厌恶；强烈反感",e:"A deep aversion to dishonesty."},
    {w:"beholden",p:"/bɪˈhəʊldən/",pos:"adj.",m:"感恩的；受恩惠的",e:"Beholden to no one."},
    {w:"bemoan",p:"/bɪˈməʊn/",pos:"v.",m:"悲叹；惋惜",e:"Bemoan the loss of tradition."},
    {w:"berate",p:"/bɪˈreɪt/",pos:"v.",m:"严厉责骂",e:"Berate someone for their mistakes."},
    {w:"blithe",p:"/blaɪð/",pos:"adj.",m:"无忧无虑的；漠不关心的",e:"Blithe disregard for danger."},
    {w:"bombastic",p:"/bɒmˈbæstɪk/",pos:"adj.",m:"夸夸其谈的；浮夸的",e:"Bombastic and empty rhetoric."},
    {w:"brazen",p:"/ˈbreɪzən/",pos:"adj.",m:"厚颜无耻的；黄铜的",e:"A brazen and shocking lie."},
    {w:"bucolic",p:"/bjuːˈkɒlɪk/",pos:"adj.",m:"田园的；乡村的",e:"A bucolic and peaceful setting."},
    {w:"burgeon",p:"/ˈbɜːrdʒən/",pos:"v.",m:"迅速发展；萌发",e:"A burgeoning new industry."},
    {w:"burnish",p:"/ˈbɜːrnɪʃ/",pos:"v.",m:"擦亮；磨光",e:"Burnish your professional reputation."},
    {w:"capricious",p:"/kəˈprɪʃəs/",pos:"adj.",m:"变化无常的；任性的",e:"Capricious and unpredictable behavior."},
    {w:"castigate",p:"/ˈkæstɪɡeɪt/",pos:"v.",m:"严厉批评；惩罚",e:"Castigate public officials harshly."},
    {w:"caustic",p:"/ˈkɔːstɪk/",pos:"adj.",m:"腐蚀性的；尖刻的",e:"Caustic and biting humor."},
    {w:"censure",p:"/ˈsenʃər/",pos:"v.",m:"谴责；责备",e:"Censure unethical behavior publicly."},
    {w:"chary",p:"/ˈtʃeəri/",pos:"adj.",m:"谨慎的；吝于给予的",e:"Be chary of false promises."},
    {w:"chicanery",p:"/ʃɪˈkeɪnəri/",pos:"n.",m:"欺骗；欺诈",e:"Political chicanery and corruption."},
    {w:"circumlocution",p:"/ˌsɜːrkəmləˈkjuːʃən/",pos:"n.",m:"迂回说法；冗赘",e:"Avoid circumlocution in all writing."},
    {w:"clairvoyant",p:"/kleəˈvɔɪənt/",pos:"adj.",m:"有洞察力的；透视的",e:"A clairvoyant insight."},
    {w:"clemency",p:"/ˈklemənsi/",pos:"n.",m:"仁慈；宽容",e:"Show clemency to the offender."},
    {w:"coalesce",p:"/ˌkəʊəˈles/",pos:"v.",m:"合并；联合",e:"The groups coalesced into one."},
    {w:"cogent",p:"/ˈkəʊdʒənt/",pos:"adj.",m:"有说服力的",e:"A cogent and compelling argument."},
    {w:"complacent",p:"/kəmˈpleɪsənt/",pos:"adj.",m:"自满的；得意的",e:"Never be complacent about success."},
  ]
};
